[package]
name = "java2rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
onlyargs = "0.1.2"
onlyargs_derive = "0.1.2"
walkdir = "2.3.3"

